### ISSUE TITLE
parsing MWSError

### ISSUE THREAD

**Issue by Mitalee** [python-amazon-mws/python-amazon-mws#218]
Hi all,
If I make a simple MWS call and get an error like the one below, is it possible right now to just do something like this:

```
except mws.mws.MWSError as e:
    print(e.code+':'+e.message)
```

Here's a sample MWS Error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/usr/local/lib/python3.6/site-packages/mws/utils.py", line 250, in _wrapped_func
    return request_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mws/mws.py", line 724, in list_marketplace_participations
    return self.make_request(data)
  File "/usr/local/lib/python3.6/site-packages/mws/mws.py", line 259, in make_request
    raise error
mws.mws.MWSError: <?xml version="1.0"?>
<ErrorResponse xmlns="https://mws.amazonservices.com/Sellers/2011-07-01">
  <Error>
    <Type>Sender</Type>
    <Code>AccessDenied</Code>
    <Message>AuthToken is not valid for SellerId and AWSAccountId.</Message>
  </Error>
  <RequestID>2e0a27e6-d3fe-4390-8019-03fabe6ce00a</RequestID>
</ErrorResponse>
```

**Comment by Bobspadger** [comment]
You are not guaranteed to get those attributes:

```python
>>> from mws import MWSError
>>> MWSError
<class 'mws.errors.MWSError'>
>>> dir(MWSError)
['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', '__weakref__', 'args', 'response', 'with_traceback']
>>>
```
You can see there are no `.text` or `.code` attributes on there.

MWSError declaration:
https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/mws.py#L61
see we only add the `response` attribute.

Example usage:
https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/mws.py#L143

**Comment by Mitalee** [comment]
Hi @Bobspadger 

> see we only add the response attribute.

Thanks for the reply. I used the response object here and I'm able to get the status code using `response.status_code` and [all other attributes of this object](https://www.w3schools.com/python/ref_requests_response.asp), very helpful.

**Comment by Bobspadger** [comment]
cool stuff 👍
