### ISSUE TITLE
Trying to run script from excel vba or batch file which is not working

### ISSUE THREAD

**Issue by azmanomer** [python-amazon-mws/python-amazon-mws#227]
Hello i'm trying to submit feed. It's working when i run script manually but when i try it with excel vba or from batch file it is not working.
For batch file the error is:
```
Traceback (most recent call last):
  File "C:\Users\omero\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 659, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "C:\Users\omero\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 279, in _get_conn
    return conn or self._new_conn()
  File "C:\Users\omero\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 947, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\omero\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\omero\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\omero\anaconda3\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mws.amazonservices.com', port=443): Max retries exceeded with url: /Feeds/2009-01-01?AWSAccessKeyId=(REDACTED)&Action=SubmitFeed&FeedType=_POST_FLAT_FILE_INVLOADER_DATA_&MarketplaceIdList.Id.1=A2EUQ1WTGCTBG2&Merchant=A34U5QPGLVNC43&PurgeAndReplace=false&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2020-10-17T19%3A17%3A13&Version=2009-01-01&Signature=(REDACTED)%3D (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\omero\Desktop\new_3.py", line 47, in <module>
    products = feeds_api.submit_feed(feed=xml.encode('utf-8'), feed_type="_POST_FLAT_FILE_INVLOADER_DATA_", marketplace_ids=marketplace_ca, content_type="text")
  File "C:\Users\omero\anaconda3\lib\site-packages\mws\apis\feeds.py", line 171, in submit_feed
    return self.make_request(
  File "C:\Users\omero\anaconda3\lib\site-packages\mws\mws.py", line 267, in make_request
    response = request(
  File "C:\Users\omero\anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\omero\anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\omero\anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\omero\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mws.amazonservices.com', port=443): Max retries exceeded with url: /Feeds/2009-01-01?AWSAccessKeyId=(REDACTED)&Action=SubmitFeed&FeedType=_POST_FLAT_FILE_INVLOADER_DATA_&MarketplaceIdList.Id.1=A2EUQ1WTGCTBG2&Merchant=A34U5QPGLVNC43&PurgeAndReplace=false&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2020-10-17T19%3A17%3A13&Version=2009-01-01&Signature=(REDACTED)%3D (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```
For excel vba i cant see what is wrong since the screen close immidiatly.
my batch file code :
```
py C:\Users\omero\Desktop\new_3.py
pause
```

my excel vba code:
```
Dim wsh As Object
Set wsh = VBA.CreateObject("WScript.Shell")
wsh.Run (Chr(34) & "C:\Users\omero\Desktop" & "\new_3.py" & Chr(34))
```

Btw i can call python scripts from vba and batch unless they have wms library thats why im writing here.
My pyhton script :
```
from mws import mws, utils
import xmltodict
from mws import Products
from mws.apis import Feeds
import time

access_key = 'xxxx'#replace with your access key
seller_id = 'xxx'#replace with your seller id
secret_key = 'xxxx'#replace with your secret key
marketplace_usa = 'ATVPDKIKX0DER'
marketplace_ca = 'A2EUQ1WTGCTBG2'
marketplace_mx = 'A1AM78C64UM0Y8'
feedfile= "C:\\Users\\omero\\Desktop\\new 3.txt"
feeds_api = Feeds(
		 access_key = access_key,
		 secret_key = secret_key,
		 account_id = seller_id,
	)
with open('C:\\Users\\omero\\Desktop\\new 3.txt' , 'r') as feedfile:
    xml = feedfile.read()
products = feeds_api.submit_feed(feed=xml.encode('utf-8'), feed_type="_POST_FLAT_FILE_INVLOADER_DATA_", marketplace_ids=marketplace_ca, content_type="text")
```

**Comment by GriceTurrble** [comment]
I don't think this in within scope for us. Those appear to be errors with trying to get SSL connections from those platforms (the first looks like anaconda?).

Can you run a barebones POST request successfully from either of those, without going through PAM?

**Comment by azmanomer** [comment]
Opps i didnt saw i that thank you.

**Comment by azmanomer** [comment]
i think i managed to fix it :)
