### ISSUE TITLE
Reports API: Max retries exceeded with url

### ISSUE THREAD

**Issue by masibenik90** [python-amazon-mws/python-amazon-mws#269]
Hello,

I am facing a problem while using mws library so I am hoping to find some help maybe. Let me try to briefly explain the issue:
So, I am using amazon mws library with Python and I am using Reports API from the link: https://docs.developer.amazonservices.com/en_US/reports/Reports_Overview.html

The application goes through 6 mws.Reports objects and requests 4 report types for each mws.Reports object.

mws.Reports objects are defined as:
    mws.Reports(
        access_key="access_key",
        secret_key="secret_key",
        account_id="account_id"
    )

The reports that are requested are:
-GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE
-GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA
-GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA
-GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA

So, for every mws.Reports object I request each report with this logic:

```
response = mws.Reports.request_report(
        report_type=report_type,
        start_date=datetime.timedelta(days=30),
        end_date=datetime.date.today()
    )
```

This operation creates a report request ID with what I further get the report status and the report itself. So, the application iterates through 6 mws.Reports objects and requests each of the mentioned report_types. And after every request there is a sleeping time of 15 seconds before the next request.

The issue appears at a halfway when performing mws.Reports.request_report operation and almost always occurs at a different time and while requesting different report This is the complete error log from one such error:

```
Task 'load': Exception encountered during task execution!
Traceback (most recent call last):
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/etl_old/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/etl_old/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/etl_old/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mws-eu.amazonservices.com', port=443): Max retries exceeded with url: /?AWSAccessKeyId="access_key"&Action=RequestReport&EndDate=2021-06-30T23%3A59%3A59&MarketplaceIdList.Id.1=APJ6JRA9NG5V4&Merchant="merchant"&ReportType=_GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA_&SignatureMethod=HmacSHA256&SignatureVersion=2&StartDate=2021-06-01T00%3A00%3A00&Timestamp=2021-07-01T15%3A56%3A59&Version=2009-01-01&Signature=hVMyqRl/Mnrd/wqh5IaOqnNMQ3WJK7itNBj9apE64Kw%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/etl_old/amazon/etl/amazon_seller_central_sellout.py", line 417, in load
    report_request_id = get_report_request_id(report_object[1], report, marketplace_id)
  File "/opt/etl_old/amazon/etl/amazon_seller_central_sellout.py", line 124, in get_report_request_id
    response = mws_object.request_report(
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/mws/mws.py", line 645, in request_report
    return self.make_request(data)
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/mws/mws.py", line 249, in make_request
    response = request(
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/etl_old/.venv/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mws-eu.amazonservices.com', port=443): Max retries exceeded with url: /?AWSAccessKeyId="access_key"&Action=RequestReport&EndDate=2021-06-30T23%3A59%3A59&MarketplaceIdList.Id.1=APJ6JRA9NG5V4&Merchant="merchant"&ReportType=_GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA_&SignatureMethod=HmacSHA256&SignatureVersion=2&StartDate=2021-06-01T00%3A00%3A00&Timestamp=2021-07-01T15%3A56%3A59&Version=2009-01-01&Signature=hVMyqRl/Mnrd/wqh5IaOqnNMQ3WJK7itNBj9apE64Kw%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

```
The weirdest thing about the error is that it started occurring recently after the application was running on the server successfully for about year and a half. And even weirder thing is that this error only occurs from the ETL server that is running the application, while when running locally from the computer everything goes well without problems. The environment from my local computer and the server is the same, with same packages and dependencies installed, so I can't figure out what could be the problem here.

Any ideas maybe?

Thanks in advance,
Marko Šibenik

**Comment by Bobspadger** [comment]
The error is coming from the SSL library when trying to do the handshake 
```
self._sslobj.do_handshake() 
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)
```

Usually this is caused because of OS level issues / connectivity issues / openssl issues etc. If the code runs correctly on your computer, but not on the server, I would be looking at what versions of this you have installed etc

From the python docs:


> exception ssl.SSLEOFError
> A subclass of SSLError raised when the SSL connection has been terminated abruptly. Generally, you shouldn’t try to reuse the underlying transport when this error is encountered.
> 
> New in version 3.3.

https://docs.python.org/3/library/ssl.html

My hunch is connectivity.

**Comment by GriceTurrble** [comment]
Separately, your access key is shown in the traceback above. Please check and potentially roll your MWS credentials to prevent unauthorized access to your account.
