### ISSUE TITLE
Wrong content length maybe amazon error 

### ISSUE THREAD

**Issue by nateshmbhat** [python-amazon-mws/python-amazon-mws#88]
It was working fine 2 days back . Now Error is popping up everytime . 
Here is my complete error traceback : It even has the reportid , get the report and please check whats the problem . 

```

report ID :  11319737708017711
Exception : Wrong Contentlength, maybe amazon error...
  File "<ipython-input-3-e36bd121ae40>", line 167, in _get_report_from_reporttype_
    resp = self.reportsapi.get_report(report_id=reportid)
  File "C:\Users\Natesh\Desktop\amazon-mws\src\mws\mws.py", line 420, in get_report
    return self.make_request(data)
  File "C:\Users\Natesh\Desktop\amazon-mws\src\mws\mws.py", line 254, in make_request
    parsed_response = DataWrapper(data, response.headers)
  File "C:\Users\Natesh\Desktop\amazon-mws\src\mws\mws.py", line 126, in __init__
    raise MWSError("Wrong Contentlength, maybe amazon error...")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\Desktop\amazon-mws\src\mws\mws.py in make_request(self, extra_data, method, **kwargs)
    247                 try:
--> 248                     parsed_response = DictWrapper(data, rootkey)
    249                 except TypeError:  # raised when using Python 3 and trying to remove_namespace()

~\Desktop\amazon-mws\src\mws\mws.py in __init__(self, xml, rootkey)
    105         self._rootkey = rootkey
--> 106         self._mydict = utils.XML2Dict().fromstring(remove_namespace(xml))
    107         self._response_dict = self._mydict.get(list(self._mydict.keys())[0], self._mydict)

~\Desktop\amazon-mws\src\mws\mws.py in remove_namespace(xml)
     97     regex = re.compile(' xmlns(:ns2)?="[^"]+"|(ns2:)|(xml:)')
---> 98     return regex.sub('', xml)
     99 

TypeError: cannot use a string pattern on a bytes-like object

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
~\Desktop\amazon-mws\src\mws\mws.py in make_request(self, extra_data, method, **kwargs)
    250                     # When we got CSV as result, we will got error on this
--> 251                     parsed_response = DictWrapper(response.text, rootkey)
    252 

~\Desktop\amazon-mws\src\mws\mws.py in __init__(self, xml, rootkey)
    105         self._rootkey = rootkey
--> 106         self._mydict = utils.XML2Dict().fromstring(remove_namespace(xml))
    107         self._response_dict = self._mydict.get(list(self._mydict.keys())[0], self._mydict)

~\Desktop\amazon-mws\src\mws\utils.py in fromstring(self, str_)
    105         """
--> 106         text = ET.fromstring(str_)
    107         root_tag, root_tree = self._namespace_split(text.tag, self._parse_node(text))

c:\program files\python35\lib\xml\etree\ElementTree.py in XML(text, parser)
   1333     parser.feed(text)
-> 1334     return parser.close()
   1335 

ParseError: no element found: line 1929, column 37

During handling of the above exception, another exception occurred:

MWSError                                  Traceback (most recent call last)
<ipython-input-3-e36bd121ae40> in _get_report_from_reporttype_(self, reporttype, olderdate, laterdate)
    166 
--> 167             resp = self.reportsapi.get_report(report_id=reportid)
    168             report = None ;

~\Desktop\amazon-mws\src\mws\mws.py in get_report(self, report_id)
    419         data = dict(Action='GetReport', ReportId=report_id)
--> 420         return self.make_request(data)
    421 

~\Desktop\amazon-mws\src\mws\mws.py in make_request(self, extra_data, method, **kwargs)
    253             except XMLError:
--> 254                 parsed_response = DataWrapper(data, response.headers)
    255 

~\Desktop\amazon-mws\src\mws\mws.py in __init__(self, data, header)
    125             if header['content-md5'].encode() != hash_:
--> 126                 raise MWSError("Wrong Contentlength, maybe amazon error...")
    127 

MWSError: Wrong Contentlength, maybe amazon error...

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-33-5b2d9a183fb9> in <module>()
----> 1 orders = obj._get_report_from_reporttype_('_GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_' , olderdate=datetime.datetime.now()-datetime.timedelta(days = 2) , laterdate=datetime.datetime.now())

<ipython-input-3-e36bd121ae40> in _get_report_from_reporttype_(self, reporttype, olderdate, laterdate)
    182             log.error('Exception : {}'.format(E)) ;
    183 
--> 184             print(resp.original)
    185 

~\Desktop\amazon-mws\src\mws\utils.py in __getattr__(self, item)
     33 
     34     def __getattr__(self, item):
---> 35         node = self.__getitem__(item)
     36 
     37         if isinstance(node, dict) and 'value' in node and len(node) == 1:

KeyError: 'original'
```

**Comment by elcolumbio** [comment]
It seems you want to access the attribute original on the object build in utils.py . That can't work you need to call it on the requests response object. But you are welcome to try the pull request. There i tried to be less confusing. I think we can close this.

**Comment by nateshmbhat** [comment]
yes ok , im now using your pull request . So far no error . thanks . Please consider merging that stable version into master version . i guess many are still cloning the master itself. It would have saved a hell lot of if i new there was this pull request earlier itself :/

**Comment by nateshmbhat** [comment]
Now the useless 'value' in being removed in the api response automatically right ?

**Comment by elcolumbio** [comment]
Yes and there are a few edge cases called cdata:
Example old for actual cdata:

'Length': {'Units': {'value': 'inches'}, 'value': '9.00'},

Example new for actual cdata:

{'#text': '2.80', '@Units': 'inches'}
