### ISSUE TITLE
Getting NewConnectionError

### ISSUE THREAD

**Issue by nateshmbhat** [python-amazon-mws/python-amazon-mws#89]
I have deployed my project on pythonanywhere . I am now using the pull request from  "https://github.com/innotrade24/python-amazon-mws1" and when I run it on local machine it works . 

The old version I was using (master branch version) was working fine in pythonanywhere. Once I used the library from pull request i am getting  this below error .

How do I fix this ?

here is the full traceback  : 

They have mentioned in this site : http://help.pythonanywhere.com/pages/403ForbiddenError/  , that it needs to use a proxy for that to work but requests module automatically handles that. But in this case I am still getting the error . Please help :/ 

 ```
 File "/home/daedalcrafters/daedal-crafters/OrderManagement/amazon_mws/interface.py", line 113, in _get_report_from_reporttype_                                                                                 
    report_request_resp = self.reportsapi.request_report(marketplace_ids=['A21TJRUUN4KGV'] , start_date= olderdate.isoformat() , end_date = laterdate.isoformat() , report_type= reporttype).parsed              
  File "/home/daedalcrafters/daedal-crafters/OrderManagement/amazon_mws/mws/apis/reports.py", line 43, in request_report                                                                                         
    return self.make_request(data)                                                                                                                                                                               
  File "/home/daedalcrafters/daedal-crafters/OrderManagement/amazon_mws/mws/mws.py", line 326, in make_request                                                                                                   
    'body', ''), headers=headers, proxies=proxies)                                                                                                                                                               
  File "/home/daedalcrafters/.virtualenvs/myenv/lib/python3.6/site-packages/requests/api.py", line 58, in request                                                                                                
    return session.request(method=method, url=url, **kwargs)                                                                                                                                                     
  File "/home/daedalcrafters/.virtualenvs/myenv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request                                                                                          
    resp = self.send(prep, **send_kwargs)                                                                                                                                                                        
  File "/home/daedalcrafters/.virtualenvs/myenv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send                                                                                             
    r = adapter.send(request, **kwargs)                                                                                                                                                                          
  File "/home/daedalcrafters/.virtualenvs/myenv/lib/python3.6/site-packages/requests/adapters.py", line 508, in send                                                                                             
    raise ConnectionError(e, request=request)                                                                                                                                                                    
Exception : HTTPSConnectionPool(host='mws.amazonservices.in', port=443): Max retries exceeded with url: /?AWSAccessKeyId=key&Action=RequestReport&EndDate=2018-06-30T06%3A50%3A54.982501&MWSAuthToken=mytoken&MarketplaceIdList.Id.1=A21TJRUUN4KGV&Merchant=A35G3R8LMVKV8X&ReportType=_GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_&SignatureMethod=HmacSHA256&SignatureVersion=2&StartDate=2018-05-31T06%3A50%3A54.982501&Timestamp=2018-06-30T06%3A50%3A55&Version=2009-01-01&Signature=TfTZhEGjqUD7TFF1gC02PMUo0GISNJ8pie5YUnoEAvU%3D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1e56950860>: Failed to establish a new connection: [Errno 111] Connection refused',))                                                                                            
^CTraceback (most recent call last):                                                                                                                                                                             
  File "/home/daedalcrafters/.virtualenvs/myenv/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn                                                                                       
    (self.host, self.port), self.timeout, **extra_kw)                                                                                                                                                            
  File "/home/daedalcrafters/.virtualenvs/myenv/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection                                                                           
    raise err                                                                                                                                                                                                    
  File "/home/daedalcrafters/.virtualenvs/myenv/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection                                                                           
    sock.connect(sa)                                                                                                                                                                                             
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by nateshmbhat** [comment]
i solved this by giving **"proxies"** argument to the **`requests.request`** method. 

request.request(url , proxies =  {'http': 'http://proxy.server:3128', 'https': 'https://proxy.server:3128'} ) 

or set the "proxy" argument when instantiating the MWS class .
